- id: tsc
  name: Typescript compiler
  description: Typescript compiler check.
  entry: tsc
  language: node
- id: eslint
  name: Typescript linter
  description: Typescript linter check.
  language: system
  entry: eslint
  language: node
- id: prettier
  name: Typescript formatter
  description: Typescript formatter check.
  entry: prettier
  language: node