- id: tsc
  name: Typescript compiler
  description: Typescript compiler check.
  entry: tsc -b 
  language: system
  types_or: [javascript, jsx, ts, tsx]
- id: eslint
  name: Typescript linter
  description: Typescript linter check.
  language: system
  entry: eslint
  types_or: [javascript, jsx, ts, tsx]
- id: prettier
  name: Typescript formatter
  description: Typescript formatter check.
  entry: prettier -w 
  language: system
  types_or: [javascript, jsx, ts, tsx]