- id: tsc
  name: Typescript compiler
  description: Typescript compiler check.
  entry: cd frontend/ && npx tsc -b ./
  language: system
  pass_filenames: false
- id: eslint
  name: Typescript linter
  description: Typescript linter check.
  language: system
  entry: cd frontend/ && npx eslint ./ --ext js,ts,jsx,tsx
- id: prettier
  name: Typescript formatter
  description: Typescript formatter check.
  entry: cd frontend/ && npx prettier -w ./
  language: system